# File modified by authors of InstructDiffusion from original (https://github.com/CompVis/stable-diffusion).
# See more details in LICENSE.

model:
  base_learning_rate: 1.0e-04
  weight_decay: 0.01
  target: ldm.models.diffusion.fmri_align.FMRIAlign
  params:
    fp16: True
    # fp16: False
    deepspeed: 'deepspeed_1'
    # deepspeed: ''
    ckpt_path: stable_diffusion/models/ldm/stable-diffusion-v1/v1-5-pruned-emaonly-adaption.ckpt
    linear_start: 0.00085
    linear_end: 0.0120
    num_timesteps_cond: 1
    log_every_t: 2000
    timesteps: 1000
    first_stage_key: edited
    cond_stage_key: edit
    fmri_cond_stage_key: fmri_edit
    image_size: 32
    channels: 4
    cond_stage_trainable: false   # Note: different from the one we trained before
    monitor: val/loss_simple_ema
    scale_factor: 0.18215

    scheduler_config: # 10000 warmup steps
      target: ldm.lr_scheduler.LambdaLinearScheduler
      params:
        warm_up_steps: [ 0 ]
        cycle_lengths: [ 10000000000000 ] # incredibly large number to prevent corner cases
        f_start: [ 1.e-6 ]
        f_max: [ 1. ]
        f_min: [ 1. ]


    # first_stage_config:
    #   target: ldm.models.autoencoder.AutoencoderKL
    #   params:
    #     embed_dim: 4
    #     monitor: val/rec_loss
    #     ddconfig:
    #       double_z: true
    #       z_channels: 4
    #       resolution: 256
    #       in_channels: 3
    #       out_ch: 3
    #       ch: 128
    #       ch_mult:
    #       - 1
    #       - 2
    #       - 4
    #       - 4
    #       num_res_blocks: 2
    #       attn_resolutions: []
    #       dropout: 0.0
    #     lossconfig:
    #       target: torch.nn.Identity

    fmri2visual_stage_config:
      target: ldm.modules.encoders.fmri_modules.FMRI2VisualEmbedder
      params:
        input_size: 7604
        output_size: 4096
        hidden_size: 256  # Adjust this as needed
        dropout_prob: 0.5  # Adjust the dropout probability as needed

data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 256
    num_workers: 8
    train:
      target: dataset.fmri.nsd_instruct_dataset.NSDInstructDataset
      params:
        nsd_root: '/data/yashengsun/Proj/MMEdit/StableDiffusionReconstruction/nsd'
        resolution: 320
        use_stim: 'each'
        subject: 'subj01'
        split: 'train'

    validation:
      target: dataset.fmri.nsd_instruct_dataset.NSDInstructDataset
      params:
        nsd_root: '/data/yashengsun/Proj/MMEdit/StableDiffusionReconstruction/nsd'
        resolution: 320
        use_stim: 'each'
        subject: 'subj01'
        split: 'val'


trainer:
  initial_scale: 13
  max_epochs: 20000
  save_freq: 500
  accumulate_grad_batches: 1
  clip_grad: 0.0
  optimizer: adamw