instructions = 
    ['Make the walls green.',
    'Remove the person.',
    'Make the windsurfer a lighthouse instead.',
    'Change it to a medieval castle.',
    'Replace it with a smoothie.',
    'Add a piece of cake.',
    'Add a castle backdrop.',
    'Make the vehicle a boat.',
    'Make him sing a song.',
    'Make it a group of airplanes.',
    'Replace board with dolphin.',
    'Make him in 3D.',
    'Add sunlight coming in from a window.',
    'Make it a rainbow train.',
    'Add a bear rug.',
    'Change the man to a woman.',
    'Turn them into llamas.',
    'Change the ball to a basketball.',
    'Add a sink.',
    'Make it in a garden.',
    'Move it to Antarctica.',
    'Replace the clocks with windows.',
    'Change the horses to elephants.',
    'Make it look like a horror movie scene.',
    'Give them a bow and arrow.',
    'Add a bumblebee hovering above the table.',
    'Change location to mountain top.',
    'Replace with a pair of cats sitting on a tree.',
    'Have her playing the guitar.',
    'Change the beverage to sparkling water.',
    'Invert the colors.',
    'Swap the bed for a couch.',
    'Replace the bathrooms with a beach backdrop.',
    'Make them all green.',
    'Add a bag of money on the top of the bus.',
    'Add more doughnuts.',
    'Replace the bat with a tennis racket.',
    'Make the boats black.',
    'Make the woman a child.',
    'Everything is on fire.',
    'Change the train to a hot air balloon.',
    'Add a rainbow.',
    'Change the flowers to yellow.',
    'Turn him into a wizard.',
    'Edit to a spaceship.',
    'Change the bus to a yellow taxi.',
    'Change the court to a beach.',
    'Make the bird pink and purple.',
    'Replace the woman with a dog.',
    'Add a sailboat in the background.',
    'Replace red fighter jets with penguins.',
    'Change the boat to a canoe.',
    'Turn the bicycle into a tricycle.',
    'Add a rainbow.',
    'Add ants crawling on the sandwiches.',
    'Make it a football player.',
    'Make them a woman.',
    'Make it a large formal dining room.',
    'Make her a redhead.',
    'Make it an abstract painting.',
    'Replace the person with a puppy.',
    'Add a magical creature.',
    'Change the skateboard to a hoverboard.',
    'Add a third person.',
    'Add a red balloon.',
    'Make it a giant gumball machine.',
    'Strip the color away.',
    'Add art deco frames.',
    'Turn it into mac and cheese.',
    'Replace kites with hot air balloons.',
    'Change the bridge to rainbow bridge.',
    'Add a kite to the scene.',
    'Change the pizza to a sandwich.',
    'Add a kite flying outside.',
    'Make the person a cartoon.',
    'Switch the bow tie to a blue one.',
    'Make the train invisible.',
    'Create a sunset scene.',
    'Make them look like they are racing.',
    'Make the surfer into a mermaid.',
    'Change the racquet to a fishing rod.',
    'Change color to yellow.',
    'Replace the frisbee with a computer.',
    'Add a stormy sky.',
    'Change the sky to night.',
    'Add in a rainbow.',
    'Make the pizza more realistic.',
    'Make them red and black.',
    'Turn the cake into a heart shape.',
    'Change the man to a seal.',
    'Add a fork.',
    'Give the cat wings.',
    'Make it a colorful refrigerator with one T-Rex inside.',
    'Replace the video game with a jigsaw puzzle.',
    'Add a monster in the sky.',
    'Make it a robot.',
    'In a distant city.',
    'Replace the skateboard with a balloon.',
    'Have a black rose petal bathmat.',
    'Add the Matterhorn in the background.',
    'With pink and blue stripes.',
    'Make the man a woman.',
    'Change the track to wooden.',
    'Replace the bicycle with a scooter.',
    'Add some tropical birds.',
    'Add dolphins swimming alongside.',
    'Change to impressionistic style.',
    'Change it to a white airplane.',
    'Change the racquet to a cricket bat.',
    'Use bright colors.',
    'Make it a daybreak ride.',
    'Make it a plate.',
    'Change the airplane to a hot air balloon.',
    'Change the laptop to a typewriter.',
    'Replace the pots and pans with swords.',
    'Paint it black.',
    'Add a cat.',
    'Add a rainbow.',
    'Replace the sinks with a bathtub.',
    'Add patterned wallpaper.',
    'Change the umbrella to a pink umbrella.',
    'Turn it into a swimming pool.',
    'Change the skis into rollerblades.',
    'Change the beach to a pier.',
    'Make it two women.',
    'Make her fly.',
    'Add color to the background.',
    'Make him into a woman.',
    'Make it more whimsical.',
    'Change the boats to submarines.',
    'Turn the giraffes into zebras.',
    'Make the table green.',
    'Replace chicken for vinegar.',
    'Make it a vintage motorcycle.',
    'Replace the bed with tree branches.',
    'Change the three people to animals.',
    'Add a mural.',
    'Change the fire hydrant to blue.',
    'Change the people to lions.',
    'Make the giraffe rainbow-colored.',
    'Make it underwater.',
    'Make it a smoothie bowl.',
    'Change the fire hydrant to a police car.',
    'Replace the skis with a kaleidoscope.',
    'Make the zebra pink.',
    'Add smiles to their faces.',
    'Replace the desktop with a laptop.',
    'Paint it in classic Renaissance style.',
    'Replace with a cheetah.',
    'Arrange in a circle.',
    'Add kittens around her.',
    'Make the racquet big huge.',
    'Make the horse a unicorn.',
    'Replace sinks with a bathtub.',
    'Replace the bus with a vintage car.',
    'Change the writing to English.',
    'Make it snowing.',
    'Make the road snowy.',
    'Take it out of the city.',
    'Make it a 3D virtual reality game.',
    'Make them unicorns.',
    'Replace the clock with a grandfather clock.',
    'Make the person a mermaid.',
    'Replace bird with a butterfly.',
    'Put a rainbow in the background.',
    'Replace broccoli with cauliflower.',
    'Make the sunglasses star-shaped.',
    'Make the scissors into jeweled scissors.',
    'Change to two dogs playing with a frisbee.',
    'Have the bird be a penguin.',
    'Add people waving from the windows.',
    'Change the plunger to a mop.',
    'Add snowmen in the background.',
    'Make the teddy bear Teddy Ruxpin.',
    'Make it into a woman on a unicorn.',
    'Insert a wacky-looking squirrel riding on the back of one of the bikes.',
    'Make the lawn a snowfield.',
    'Swap the woman and the giraffe.',
    'Add a tumbleweed.',
    'Add a lake in the background.',
    'Change to a snowboarder.',
    'Make all the baskets purple.',
    'Add beautiful fall colors.',
    'Make the pillow a Union Jack pillow.',
    'Make the people into cats.',
    'Replace the coach with an armchair.',
    'Change it to rush hour.',
    'At sunset.',
    'Have the trees be palm trees.',
    'Add a girl with a parrot on her shoulder.',
    'Add American flags.',
    'Make him an astronaut.',
    'Add an orange sunset.',
    'Add salads.',
    'Add snow.',
    'Add in some autumn leaves.',
    'Change the building to an old castle.',
    'Add laptops.',
    'Replace the 4-way sign with a "yield" sign.',
    'Add mountains in the background.',
    'Replace them with a steampunk airship.',
    'Make it an outdoor bathroom.',
    'Change the sectional sofa to a round couch.',
    'Replace airplane with hot air balloon.',
    'Make them all pumpkins.',
    'Make it a woman.',
    'Change the hot dogs to pizza.',
    'Change the pizza to a calzone.',
    'Change the Nintendo Wii to Playstation 5.',
    'Make the time 5:17.',
    'Turn them into robots.',
    'Have the man contain constellations.',
    'Make it a zebra.',
    'Make it a blue umbrella.',
    'Change the lights to Christmas colors.',
    'Make them wearing a superhero costume.',
    'Add a rainbow in the sky.',
    'Turn it into a painting.',
    'Change the silver train to a yellow bus.',
    'Change to a smaller train.',
    'Replace the vanity with a sink.',
    'Make it a woman.',
    'Add a siren sound.',
    'Add a spectral forest in the background.',
    'Replace with a hiking trip.',
    'Change the angle to a high view.',
    'The boat is painted blue.',
    'Replace the kite with a hot air balloon.',
    'Replace the cat with a dog.',
    'Make the umbrellas rainbow-colored.',
    'Replace man with a woman.',
    'Replace wooden skateboard with a hoverboard.',
    'Change the ship to an airplane.',
    'Paint all the buildings yellow.',
    'Add a fourth dish.',
    'Change the person into a robot.',
    'Make it abstract.',
    'Replace hay with sea grass.',
    'Replace the cups with lemons.',
    'Swap the person with a Yeti.',
    'Make it a bicycle.',
    'Add a steampunk feel.',
    'Make the bed pink.',
    'The water is icy.',
    'Replace the people with dragons.',
    'And they are wearing crowns.',
    'Make him a snowboarder.',
    'Change the dog to a lion.',
    'Add ants walking around the pizza.',
    'Replace the hill with a half-pipe.',
    'At night.',
    'Make it a cobblestone street.',
    'Make them look like they are fishing.',
    'Make the truck a hot air balloon.',
    'Make everything pink.',
    'Make it into a cartoon.',
    'Add butterflies and birds to the stage.',
    'Make him ride a surfboard.',
    'Make the field covered in snow.',
    'Add a puddle of water below it.',
    'Add a few slices missing.',
    'Add a bone in its mouth.',
    'Add a fireplace on the wall.',
    'Change the table to a white boat on a lake.',
    'Replace the helicopter with a fighter jet.',
    'Add a bowtie.',
    'Make it an old man.',
    'Make it blue.',
    'Turn the clock tower into a fireworks display.',
    'Put gangsters in the boats.',
    'Change the color of the clock.',
    'Change the scene to a jungle.',
    'Make it look like a movie set.',
    'Make it look like a cartoon.',
    'Give the woman a laptop.',
    'Make it a spaceship flying through the stars.',
    'Change the curtains to tie-dyed fabric.',
    'Add a thunderstorm.',
    'Add a heart in the sky.',
    'Change man to woman.',
    'Add a bright sunset background.',
    'Swap the yellow umbrella for a lavender parasol.',
    'Make him slide into home plate.',
    'Make the man a robot.',
    'Replace the flowers with a laptop.',
    'Change the lights to multicolored LED lights.',
    'Change the man to a woman.',
    'Make the bed.',
    'Make it twilight.',
    'Replace racket with bow and arrow.',
    'Replace the television with a robotic arm.',
    'Replace the countryside with a big city.',
    'Change the girl to a young boy.',
]

entities = [
    'Walls',
    'Person',
    'Person',
    'The entire scene',
    'The entire scene',
    'Foreground',
    'Background',
    'Vehicle',
    'Person',
    'The entire scene',
    'Board',
    'Person',
    'Sunlight',
    'Train',
    'Rug',
    'Man',
    'People',
    'Ball',
    'Sink',
    'The entire scene',
    'The entire scene',
    'Clocks',
    'Horses',
    'The entire scene',
    'People',
    'Bumblebee',
    'Location',
    'Foreground',
    'Person',
    'Beverage',
    'The entire scene',
    'Bed',
    'Bathrooms',
    'Foreground',
    'Money',
    'Doughnuts',
    'Bat',
    'Boats',
    'Woman',
    'The entire scene',
    'Train',
    'Rainbow',
    'Flowers',
    'Person',
    'The entire scene',
    'Bus',
    'Court',
    'Bird',
    'Woman',
    'Background',
    'Red fighter jets',
    'Boat',
    'Bicycle',
    'Rainbow',
    'Sandwiches',
    'person',
    'People',
    'The entire scene',
    'Person',
    'The entire scene',
    'Person',
    'Foreground',
    'Skateboard',
    'person',
    'Red balloon',
    'Foreground',
    'The entire scene',
    'Art deco frames',
    'The entire scene',
    'Kites',
    'Bridge',
    'Kite',
    'Pizza',
    'Kite',
    'Person',
    'Bow tie',
    'Train',
    'The entire scene',
    'People',
    'Surfer',
    'Racquet',
    'Color',
    'Frisbee',
    'Sky',
    'Sky',
    'Rainbow',
    'Pizza',
    'People',
    'Cake',
    'Man',
    'Fork',
    'Cat',
    'Refrigerator',
    'Video game',
    'Monster',
    'The entire scene',
    'The entire scene',
    'Skateboard',
    'Bathmat',
    'Background',
    'The entire scene',
    'Man',
    'Track',
    'Bicycle',
    'Birds',
    'Dolphins',
    'The entire scene',
    'Airplane',
    'Racquet',
    'The entire scene',
    'The entire scene',
    'Foreground',
    'Airplane',
    'Laptop',
    'Pots and pans',
    'The entire scene',
    'Cat',
    'Rainbow',
    'Sinks',
    'Wallpaper',
    'Umbrella',
    'The entire scene',
    'Skis',
    'Beach',
    'People',
    'Person',
    'Background',
    'Person',
    'The entire scene',
    'Boats',
    'Giraffes',
    'Table',
    'Chicken',
    'Motorcycle',
    'Bed',
    'People',
    'Mural',
    'Fire hydrant',
    'People',
    'Giraffe',
    'The entire scene',
    'Foreground',
    'Fire hydrant',
    'Skis',
    'Zebra',
    'Faces',
    'Desktop',
    'The entire scene',
    'Foreground',
    'The entire scene',
    'Kittens',
    'Racquet',
    'Horse',
    'Sinks',
    'Bus',
    'The entire scene',
    'The entire scene',
    'Road',
    'The entire scene',
    'The entire scene',
    'People',
    'Clock',
    'Person',
    'Bird',
    'Background',
    'Broccoli',
    'Sunglasses',
    'Scissors',
    'Dogs',
    'Bird',
    'People',
    'Plunger',
    'Snowmen',
    'Teddy bear',
    'Foreground',
    'Squirrel',
    'Lawn',
    'Woman and giraffe',
    'Tumbleweed',
    'Lake',
    'Foreground',
    'Baskets',
    'The entire scene',
    'Pillow',
    'People',
    'Coach',
    'The entire scene',
    'The entire scene',
    'Trees',
    'Girl',
    'American flags',
    'Person',
    'Sunset',
    'Salads',
    'Snow',
    'Autumn leaves',
    'Building',
    'Laptops',
    'Sign',
    'Background',
    'People',
    'Bathroom',
    'Sectional sofa',
    'Airplane',
    'People',
    'person',
    'Hot dogs',
    'Pizza',
    'Nintendo Wii',
    'Time',
    'People',
    'Man',
    'Foreground',
    'Umbrella',
    'Lights',
    'People',
    'Rainbow',
    'The entire scene',
    'Train',
    'Train',
    'Vanity',
    'person',
    'Sound',
    'Background',
    'The entire scene',
    'Angle',
    'Boat',
    'Kite',
    'Cat',
    'Umbrellas',
    'Man',
    'Skateboard',
    'Ship',
    'Buildings',
    'Dish',
    'Person',
    'The entire scene',
    'Hay',
    'Cups',
    'Person',
    'Foreground',
    'The entire scene',
    'Bed',
    'Water',
    'People',
    'The entire scene',
    'Person',
    'Dog',
    'Ants',
    'Hill',
    'The entire scene',
    'Street',
    'People',
    'Truck',
    'The entire scene',
    'The entire scene',
    'Butterflies and birds',
    'Person',
    'Field',
    'Puddle',
    'Pizza',
    'Foreground',
    'Fireplace',
    'Table',
    'Helicopter',
    'Bowtie',
    'person',
    'The entire scene',
    'Clock tower',
    'Boats',
    'Clock',
    'Scene',
    'The entire scene',
    'The entire scene',
    'Woman',
    'The entire scene',
    'Curtains',
    'Thunderstorm',
    'Heart',
    'Man',
    'Background',
    'Umbrella',
    'Person',
    'Man',
    'Flowers',
    'Lights',
    'Man',
    'Bed',
    'The entire scene',
    'Racket',
    'Television',
    'Countryside',
    'Girl',
]
### first 300 items

instruction_entity_dict = dict(zip(instructions, entities))
